CREATE TABLE USUARIO (
  ID int PRIMARY KEY IDENTITY,
  NOME varchar(30),
  EMAIL varchar(50)
);

CREATE TABLE PROJETO (
  ID int PRIMARY KEY,
  NOME varchar(30),
  DESCRICAO varchar(50)
);

CREATE TABLE CATEGORIA (
  ID int PRIMARY KEY,
  NOME varchar(30)
);

CREATE TABLE TAREFA (
  ID int PRIMARY KEY,
  TITULO varchar(30),
  DESCRICAO varchar(50),
  PROJETO_ID INT FOREIGN KEY references PROJETO(ID),
  RESPONSAVEL_ID INT FOREIGN KEY REFERENCES USUARIO(ID),
  CATEGORIA_ID INT FOREIGN KEY REFERENCES CATEGORIA(ID),
  PRIORIDADE varchar(1),
  STATUS varchar(2),
  DATA_CRIACAO DATE,
  PRAZO DATE
);